/** Neutral Svolo badges identify configured providers without loading vendor art.
 * Provider names remain labels; these tiles do not claim provider endorsement. */
export interface ProviderBadge { label: string; background: string; color: string; }
const badge = (label: string): ProviderBadge => ({ label, background: "var(--accent-soft)", color: "var(--accent)" });
export const BADGES: Record<string, ProviderBadge> = {
  AntLing: badge("AL"),
  Anthropic: badge("AN"),
  Azure: badge("AZ"),
  Baseten: badge("BA"),
  Bedrock: badge("BR"),
  Cerebras: badge("CE"),
  ClaudeCode: badge("CC"),
  Cloudflare: badge("CF"),
  DeepSeek: badge("DS"),
  Fireworks: badge("FW"),
  GithubCopilot: badge("GC"),
  Google: badge("GO"),
  Groq: badge("GQ"),
  HuggingFace: badge("HF"),
  Kimi: badge("KI"),
  Meta: badge("ME"),
  Minimax: badge("MM"),
  Mistral: badge("MI"),
  Moonshot: badge("MO"),
  Nvidia: badge("NV"),
  OpenAI: badge("AI"),
  OpenCode: badge("OC"),
  OpenRouter: badge("OR"),
  Qwen: badge("QW"),
  Radius: badge("RA"),
  Together: badge("TO"),
  TypeSafe: badge("TS"),
  Vercel: badge("VE"),
  VertexAI: badge("VA"),
  XAI: badge("XA"),
  XiaomiMiMo: badge("XM"),
  ZAI: badge("ZA"),
};

export const PROVIDER_IDENTITIES: Record<string, string> = {
  "amazon-bedrock": "Bedrock",
  "ant-ling": "AntLing",
  "anthropic": "Anthropic",
  "azure-openai-responses": "Azure",
  "baseten": "Baseten",
  "cerebras": "Cerebras",
  "claude-bridge": "ClaudeCode",
  "cloudflare-ai-gateway": "Cloudflare",
  "cloudflare-workers-ai": "Cloudflare",
  "deepseek": "DeepSeek",
  "fireworks": "Fireworks",
  "github-copilot": "GithubCopilot",
  "google": "Google",
  "google-vertex": "VertexAI",
  "groq": "Groq",
  "huggingface": "HuggingFace",
  "kimi-coding": "Kimi",
  "meta": "Meta",
  "minimax": "Minimax",
  "minimax-cn": "Minimax",
  "mistral": "Mistral",
  "moonshotai": "Moonshot",
  "moonshotai-cn": "Moonshot",
  "nvidia": "Nvidia",
  "openai": "OpenAI",
  "openai-codex": "OpenAI",
  "opencode": "OpenCode",
  "opencode-go": "OpenCode",
  "openrouter": "OpenRouter",
  "qwen-token-plan": "Qwen",
  "qwen-token-plan-cn": "Qwen",
  "qwen-token-plan-individual": "Qwen",
  "radius": "Radius",
  "together": "Together",
  "typesafe": "TypeSafe",
  "vercel-ai-gateway": "Vercel",
  "xai": "XAI",
  "xiaomi": "XiaomiMiMo",
  "xiaomi-token-plan-ams": "XiaomiMiMo",
  "xiaomi-token-plan-cn": "XiaomiMiMo",
  "xiaomi-token-plan-sgp": "XiaomiMiMo",
  "zai": "ZAI",
  "zai-coding-cn": "ZAI"
};
