import test from 'node:test';import assert from 'node:assert/strict';import {readFile,mkdir,writeFile}from'node:fs/promises';import{resolve,sep,extname}from'node:path';import{fileURLToPath}from'node:url';import {nativeBrowser,browserAvailable}from'./test-browser.mjs';
const root=resolve(process.env.SVOLO_FRONTEND_ROOT??fileURLToPath(new URL('public/',import.meta.url)));const brandRoot=resolve(fileURLToPath(new URL('../brand/',import.meta.url)));
test('native frontend chat actions, both languages, draft continuity and collapsing column',{skip:browserAvailable?false:'Native browser unavailable'},async t=>{
 let loggedIn=true,sessions=[{id:'alpha',name:'Original chat',pinned:false},{id:'beta',name:'Another chat',pinned:false}];const mutations=[];let taskProfiles=[],taskFiles=[],taskSelections={},proposals=[],learnRuns=[];const versions=new Map();
 const handler=async(req,res)=>{const url=new URL(req.url,'http://fixture');const json=(value,status=200)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(value));};
 if(url.pathname.startsWith('/api/')){
  let payload;if(!['GET','HEAD'].includes(req.method)){let bytes='';for await(const part of req)bytes+=part;payload=req.headers['content-type']==='application/octet-stream'?{content:bytes}:bytes?JSON.parse(bytes):{};assert.equal(req.headers['x-csrf-token'],'fixture-csrf');mutations.push({path:url.pathname,method:req.method,payload});}
  if(url.pathname==='/api/me'){json(loggedIn?{user:{id:'fixture',username:'FixtureUser',role:'admin'},csrf:'fixture-csrf'}:{error:'Sign in required'},loggedIn?200:401);return true}
  if(url.pathname==='/api/logout'){loggedIn=false;json({ok:true});return true}
  if(url.pathname==='/api/task-profiles'){if(req.method==='POST'){const p={id:'task-fixture',name:payload.name,knowledge:'Starter procedure: verify the current form.',uploadOrigins:payload.uploadOrigins||[],revision:1};taskProfiles.push(p);versions.set(p.id,[{...p}]);json(p,201)}else if(req.method==='PATCH'){const p=taskProfiles.find(p=>p.id===url.searchParams.get('id'));Object.assign(p,payload,{revision:p.revision+1});versions.get(p.id).unshift({...p});json(p)}else if(req.method==='DELETE'){taskProfiles=taskProfiles.filter(p=>p.id!==url.searchParams.get('id'));json({deleted:true})}else json({profiles:taskProfiles});return true}
  if(url.pathname==='/api/task-profiles/versions'){json({versions:versions.get(url.searchParams.get('id'))});return true}
  if(url.pathname==='/api/documents/capabilities'){json({ocr:true,pdfText:true});return true}
  if(url.pathname==='/api/task-selection'){const sid=url.searchParams.get('session');if(req.method==='POST')taskSelections[sid]=payload.profileId;json({profileId:taskSelections[sid]||''});return true}
  if(url.pathname==='/api/attachments'){if(req.method==='POST'){const doc={id:'doc-'+taskFiles.length,name:url.searchParams.get('name'),session:url.searchParams.get('session'),mime:'text/plain',method:'utf8',text:payload.content,size:payload.content.length,partial:false};taskFiles.push(doc);json(doc,201)}else if(req.method==='DELETE'){taskFiles=taskFiles.filter(d=>d.id!==url.searchParams.get('id'));json({deleted:true})}else json({attachments:taskFiles.filter(d=>d.session===url.searchParams.get('session'))});return true}
  if(url.pathname==='/api/attachments/text'){json(taskFiles.find(d=>d.id===url.searchParams.get('id')));return true}
  if(url.pathname==='/api/task-profiles/proposals'){if(req.method==='POST'){const p=proposals.find(p=>p.id===url.searchParams.get('id'));if(payload.approve){const profile=taskProfiles.find(x=>x.id===p.profileId);profile.knowledge=payload.knowledge;profile.revision++;versions.get(profile.id).unshift({...profile});}proposals=proposals.filter(p=>p.id!==url.searchParams.get('id'));json({saved:payload.approve})}else json({proposals});return true}
  if(url.pathname==='/api/providers'){json({providers:[{id:'fixture',name:'Fixture provider',kind:'openai-compatible',configured:true,models:[{id:'fixture-model',name:'Fixture model'}],quota:{status:'unavailable'}}],defaultProvider:'fixture',defaultModel:'fixture-model'});return true}
  if(url.pathname==='/api/sessions'){
   if(req.method==='GET')json([...sessions].sort((a,b)=>Number(b.pinned)-Number(a.pinned)));
   else if(req.method==='PATCH'){const item=sessions.find(s=>s.id===url.searchParams.get('id'));Object.assign(item,payload);json(item)}
   else if(req.method==='DELETE'){sessions=sessions.filter(s=>s.id!==url.searchParams.get('id'));json({deleted:true})}
   else if(req.method==='POST'){const item={id:'new-fixture',name:payload.name,pinned:false};sessions.push(item);json(item,201)}return true;
  }
  if(url.pathname==='/api/mcp'){json({servers:[{id:'fixture',name:'Fixture MCP',url:'https://fixture.example/mcp',connected:true}]});return true}
  if(url.pathname==='/api/users'){json({users:[{id:'fixture',username:'FixtureUser',role:'admin'}]});return true}
  if(url.pathname==='/api/core/v1/runs'){if(req.method==='POST'){const run={id:'learn-fixture-run',session:payload.session,status:'completed',text:'Learning proposed for review',prompt:payload.prompt,steps:1,started:new Date().toISOString()};learnRuns.push(run);const p=taskProfiles.find(p=>p.id===taskSelections[payload.session]);proposals.push({id:'proposal-fixture',profileId:p.id,baseRevision:p.revision,knowledge:'Verified mapping: offer.plan → Plan field. Verify the confirmation receipt.',reason:'Verified field mapping',session:payload.session});json(run);return true}if(learnRuns.length){json(learnRuns);return true}json(sessions.some(s=>s.id==='alpha')?[{id:'fixture-run',session:'alpha',status:'completed',model:'fixture-model',text:'## Contenuto utente\n\n**Non tradurre**\n\n| Test | Value |\n|---|---|\n| User | 2 |',prompt:'Messaggio italiano dell’utente',steps:2,started:'2026-10-06T00:00:00Z'}]:[]);return true}
  if(url.pathname==='/api/core/v1/control'){json({owner:'human',epoch:1});return true}
  if(['/api/core/v1/events','/api/core/v1/approvals','/api/core/v1/browser/tabs'].includes(url.pathname)){json([]);return true}
  if(url.pathname==='/api/core/v1/health'){json({ok:true});return true}
  json({error:'Fixture route not configured'},404);return true;
 }
 const pathname=url.pathname==='/'?'/index.html':url.pathname;if(pathname.startsWith('/brand/')){const asset=resolve(brandRoot,'.'+pathname.slice(6));if(!asset.startsWith(brandRoot+sep))return false;try{res.writeHead(200,{'Content-Type':{'.svg':'image/svg+xml','.webp':'image/webp','.png':'image/png'}[extname(asset)]??'application/octet-stream'});res.end(await readFile(asset));return true}catch{return false}}
 const path=resolve(root,'.'+pathname);if(!path.startsWith(root+sep))return false;
 try{const data=await readFile(path);const type={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css'}[extname(path)]??'application/octet-stream';res.writeHead(200,{'Content-Type':type});res.end(data);return true}catch{return false}
 };
 const {evaluate,client}=await nativeBrowser(t,{handler,ready:'!!document.querySelector(".landing")'});
 const capture=async name=>{if(!process.env.SVOLO_FRONTEND_CAPTURE_DIR)return;await mkdir(process.env.SVOLO_FRONTEND_CAPTURE_DIR,{recursive:true,mode:0o700});const {data}=await client.call('Page.captureScreenshot',{format:'png'});await writeFile(resolve(process.env.SVOLO_FRONTEND_CAPTURE_DIR,name+'.png'),Buffer.from(data,'base64'),{mode:0o600});};
 const wait=async expression=>{const limit=Date.now()+8000;while(Date.now()<limit){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,25))}throw Error('Frontend condition timed out: '+expression)};
 const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
 const lang=async selected=>{await wait('!!document.querySelector("button[data-language]")');if(await evaluate('document.documentElement.lang')!==selected)await click('[data-action="toggle-language"]');await wait(`document.documentElement.lang===${JSON.stringify(selected)} && document.querySelector('[data-language]')?.dataset.language===${JSON.stringify(selected)} && !document.querySelector('[data-language]').disabled`);};
 const navigate=async hash=>{await evaluate(`location.hash=${JSON.stringify(hash)}`);await wait(hash.startsWith('#settings')?'!!document.querySelector(".settings-tabs")':'!!document.querySelector("#prompt")')};
 assert.equal(await evaluate('document.documentElement.lang'),'en');assert.match(await evaluate('document.querySelector("h1").textContent'),/direction/i);assert.equal(await evaluate('document.documentElement.dataset.theme'),'dark');
 await navigate('#workspace');await wait('!!document.querySelector(".message.assistant table")');
 assert.match(await evaluate('document.querySelector(".message.assistant").textContent'),/Non tradurre/);assert.match(await evaluate('document.querySelector(".message.user").textContent'),/Messaggio italiano/);
 assert.match(await evaluate('document.querySelector("#agent-status").textContent'),/Ready/i);
 await click('[data-session=beta] + .session-menu summary');await wait('document.querySelector("[data-session=beta] + .session-menu").open');assert.equal(await evaluate('(()=>{const button=document.querySelector("[data-chat-action=pin][data-chat-id=beta]"),box=button.getBoundingClientRect();return button.contains(document.elementFromPoint(box.x+10,box.y+10));})()'),true,'Chat menu must remain clickable outside the scrolling list');await click('[data-chat-action="pin"][data-chat-id="beta"]');await wait('document.querySelector("[data-session]").dataset.session==="beta"');
 await click('[data-chat-action="rename"][data-chat-id="beta"]');await wait('document.querySelector("#modal").open');await evaluate('document.querySelector("#modal input[name=name]").value="Pinned renamed";document.querySelector("#modal-form").requestSubmit()');await wait('document.querySelector("[data-session=beta]").textContent.includes("Pinned renamed")');
 await evaluate('document.querySelector("#prompt").value="Unsent **draft**"');await lang('it');await wait('document.querySelector("#prompt")?.value==="Unsent **draft**"');assert.match(await evaluate('document.querySelector("#new-session").textContent'),/Nuova/);
 await wait('document.querySelector("#agent-status").textContent.includes("Pronto")');await lang('en');await wait('document.querySelector("#prompt")?.value==="Unsent **draft**"');
 assert.equal(await evaluate('!!document.querySelector("#chat-panel #toggle-chat")'),true);assert.equal(await evaluate('!!document.querySelector(".workspace-top #toggle-chat")'),false);assert.equal(await evaluate('document.querySelectorAll("select[data-language]").length'),0);
 await capture('columns-open');await click('#toggle-chat');assert.equal(await evaluate('getComputedStyle(document.querySelector("#chat-panel")).display'),'none');assert.equal(await evaluate('document.querySelector("#chat-panel").inert'),true);
 assert.equal(await evaluate('document.querySelector("#expand-chat").hidden'),false);assert.equal(await evaluate('document.activeElement.id'),'expand-chat');
 assert.equal(await evaluate('(()=>{const button=document.querySelector("#expand-chat"),box=button.getBoundingClientRect();return button.contains(document.elementFromPoint(box.x+box.width/2,box.y+box.height/2));})()'),true,'Floating chat button must be visible and clickable');
 const browserWidth=await evaluate('document.querySelector(".browser-panel").getBoundingClientRect().width');
 await click('#toggle-sidebar');assert.equal(await evaluate('Math.round(document.querySelector(".sidebar").getBoundingClientRect().width)'),72);assert.equal(await evaluate('getComputedStyle(document.querySelector(".sidebar-section")).display'),'none');assert.equal(await evaluate('getComputedStyle(document.querySelector(".logo>span")).display'),'none');assert.notEqual(await evaluate('getComputedStyle(document.querySelector(".side-nav svg")).display'),'none');assert.notEqual(await evaluate('getComputedStyle(document.querySelector(".profile-button .avatar")).display'),'none');assert.equal(await evaluate('getComputedStyle(document.querySelector(".profile-label")).display'),'none');assert.ok(await evaluate('document.querySelector(".browser-panel").getBoundingClientRect().width')>browserWidth);
 assert.equal(await evaluate('(()=>{const badge=document.querySelector("#view-status").getBoundingClientRect(),button=document.querySelector("#expand-chat").getBoundingClientRect();return badge.right<=button.left;})()'),true,'Reopen button must not cover browser status');assert.equal(await evaluate('(()=>{const box=document.querySelector(".profile-button").getBoundingClientRect();return innerHeight-box.bottom<40;})()'),true,'Compact profile remains at the bottom');
 await capture('columns-collapsed');await evaluate('window.__beforeReload=true');await client.call('Page.reload');await wait('!window.__beforeReload && !!document.querySelector(".workspace.sidebar-collapsed .chat-collapsed") && !!document.querySelector("#toggle-sidebar")');assert.equal(await evaluate('document.querySelector("#toggle-sidebar").getAttribute("aria-expanded")'),'false');
 await client.call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});await wait('document.querySelector("#chat-panel").inert===false');assert.equal(await evaluate('getComputedStyle(document.querySelector("#expand-chat")).display'),'none');await click('#mobile-menu');assert.equal(await evaluate('document.querySelector(".workspace").classList.contains("sidebar-open")'),true);assert.notEqual(await evaluate('getComputedStyle(document.querySelector(".sidebar-section")).display'),'none');await click('#mobile-menu');assert.notEqual(await evaluate('getComputedStyle(document.querySelector("#chat-panel")).display'),'none');assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);
 await client.call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await wait('document.querySelector("#chat-panel").inert===true');await click('#expand-chat');assert.equal(await evaluate('document.querySelector("#expand-chat").hidden'),true);assert.equal(await evaluate('document.activeElement.id'),'toggle-chat');await evaluate('document.querySelector("#prompt").value="Unsent **draft**"');await click('#toggle-chat');await click('#expand-chat');assert.equal(await evaluate('document.querySelector("#prompt").value'),'Unsent **draft**');await capture('sidebar-compact-chat-open');await click('#toggle-sidebar');assert.notEqual(await evaluate('getComputedStyle(document.querySelector(".sidebar-section")).display'),'none');
 await click('[data-chat-action="delete"][data-chat-id="alpha"]');await wait('document.querySelector("#modal").open');assert.match(await evaluate('document.querySelector("#modal-form [type=submit]").textContent'),/Delete/);await evaluate('document.querySelector("#modal-form").requestSubmit()');await wait('!document.querySelector("[data-session=alpha]")&&!document.querySelector("#modal").open');
 for(const selected of ['en','it']){await lang(selected);for(const page of ['providers','mcp','users','account']){await navigate('#settings/'+page);await wait('!!document.querySelector("#settings-content h2")');assert.equal(await evaluate('document.querySelector("[data-language]").dataset.language'),selected);if(page==='providers'){await click('#add-provider');assert.match(await evaluate('document.querySelector("#modal").textContent'),selected==='en'?/API key/i:/Chiave API/);await click('#modal-cancel')}if(page==='mcp'){await click('#add-mcp');assert.match(await evaluate('document.querySelector("#modal").textContent'),selected==='en'?/credential/i:/Credenziale/);await click('#modal-cancel')}}}
 assert.equal(mutations.filter(x=>x.path.startsWith('/api/core')).length,0,'layout/language changes never mutate browser or agent state');
 await lang('en');await navigate('#settings/tasks');await click('#tim-starter');await wait('!!document.querySelector("[data-edit-task]")');await click('[data-edit-task]');await wait('document.querySelector("#modal").open');await evaluate('document.querySelector("#modal [name=knowledge]").value="Map source.plan to Plan. Verify the final receipt.";document.querySelector("#modal [name=origins]").value="https://portal.example";document.querySelector("#modal [name=reviewed]").checked=true;document.querySelector("#modal-form").requestSubmit()');await wait('!document.querySelector("#modal").open && document.querySelector(".task-profile-list").textContent.includes("v2")');
 await navigate('#workspace');await wait('document.querySelector("#task-select").value==="task-fixture"');assert.match(await evaluate('document.querySelector("#document-files").accept'),/\.jpg.*\.png.*\.pdf.*\.txt.*\.csv/);
 await evaluate('(()=>{const data=new DataTransfer();data.items.add(new File(["TEST QUOTE <script>unsafe()</script>"],"quote.txt",{type:"text/plain"}));const input=document.querySelector("#document-files");input.files=data.files;input.dispatchEvent(new Event("change",{bubbles:true}));})()');await wait('!!document.querySelector("[data-document]") && !document.querySelector("#attach-file").disabled');assert.equal(await evaluate('document.querySelector("[data-document]").checked'),true);
 await click('[data-preview-document]');await wait('document.querySelector("#modal").open');assert.match(await evaluate('document.querySelector("#modal textarea").value'),/<script>/);assert.equal(await evaluate('document.querySelectorAll("#modal script").length'),0);await click('#modal-cancel');
 await lang('it');await wait('!!document.querySelector("#task-select")');assert.equal(await evaluate('document.querySelector("[data-document]").checked'),true);assert.match(await evaluate('document.querySelector("#document-notice").textContent'),/Solo i file/);await lang('en');await evaluate('document.querySelector("#prompt").value="Keep this unsent draft"');await click('#learn-task');await wait('!!document.querySelector("[data-review-learning]")');await wait('document.querySelector("#prompt")?.value==="Keep this unsent draft"');await click('[data-review-learning]');await wait('document.querySelector("#modal").open');assert.equal(await evaluate('document.querySelector("#modal [name=reviewed]").checked'),false);await evaluate('document.querySelector("#modal [name=reviewed]").checked=true;document.querySelector("#modal-form").requestSubmit()');await wait('!document.querySelector("#modal").open && !document.querySelector("[data-review-learning]")');await navigate('#settings/tasks');assert.match(await evaluate('document.querySelector(".task-profile-list").textContent'),/v3/);
 await click('[data-task-versions]');await wait('document.querySelector("#modal").open');assert.equal(await evaluate('document.querySelector("#task-history-version").options.length'),3);await click('#modal-cancel');
 await client.call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});await navigate('#workspace');assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);await capture('documents-task-mobile');await client.call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await capture('documents-task-desktop');await navigate('#settings/account');
 await lang('en');await click('#logout');await wait('!!document.querySelector("#login-form")');await evaluate('document.querySelector("[name=username]").value="UnsubmittedUser"');await lang('it');await wait('document.querySelector("[name=username]")?.value==="UnsubmittedUser"');assert.match(await evaluate('document.querySelector(".auth-card h2").textContent'),/Bentornato/);
 await evaluate('window.__beforeReload=true');await client.call('Page.reload');await wait('!window.__beforeReload && document.documentElement.lang==="it" && !!document.querySelector("#login-form")');await lang('en');assert.match(await evaluate('document.querySelector(".auth-card h2").textContent'),/Welcome/);
 assert.ok(mutations.some(x=>x.method==='PATCH'&&x.payload.pinned===true));assert.ok(mutations.some(x=>x.method==='PATCH'&&x.payload.name==='Pinned renamed'));assert.ok(mutations.some(x=>x.method==='DELETE'));assert.equal(mutations.filter(x=>x.path.startsWith('/api/core')&&x.path!=='/api/core/v1/runs').length,0,'task learning does not mutate browser control');
});
