import test from 'node:test';import assert from 'node:assert/strict';import {randomBytes} from 'node:crypto';import {mkdtempSync,writeFileSync,readFileSync,rmSync,statSync,readdirSync,symlinkSync,unlinkSync,existsSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {openDatabase} from './database.mjs';import {createTaskStore,assertReusable} from './tasks.mjs';import {createDocumentReader,documentType} from './documents.mjs';import {nativeBrowser,browserAvailable} from './test-browser.mjs';
const alice='a'.repeat(32),bob='b'.repeat(32);
function fixture(t){const root=mkdtempSync(join(tmpdir(),'svolo-tasks-')),keyFile=join(root,'fixture.key'),dataDir=join(root,'data');writeFileSync(keyFile,randomBytes(32).toString('hex'),{mode:0o600});const store=openDatabase(dataDir,keyFile);for(const [id,name]of[[alice,'FixtureAlice'],[bob,'FixtureBob']])store.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?)').run(id,name,'not-a-password-hash','user',0,new Date().toISOString());const reader=createDocumentReader({tempRoot:join(root,'decode'),ocrPrefix:process.env.SVOLO_OCR_PREFIX});const tasks=createTaskStore({...store,dataDir,reader});t.after(()=>{if(store.db.isOpen)store.db.close();rmSync(root,{recursive:true,force:true});});return {...store,tasks,reader,root,dataDir,keyFile};}
test('task procedures are private, encrypted, reviewed, versioned and durable',async t=>{const f=fixture(t),p=f.tasks.saveProfile(alice,{name:'Fixture contract workflow',knowledge:'Read the offer, then verify the portal fields.',uploadOrigins:['https://portal.example'],reviewed:true});assert.throws(()=>f.tasks.getProfile(bob,p.id),{status:404});assert.throws(()=>f.tasks.saveProfile(bob,{name:'Other',knowledge:'',revision:1},p.id),{status:404});assert.throws(()=>f.tasks.saveProfile(alice,{...p,knowledge:'New procedure',reviewed:false},p.id),/Review/);assert.throws(()=>f.tasks.saveProfile(alice,{...p,knowledge:'New procedure',template:'unsupported',reviewed:false},p.id),/templates/);const v2=f.tasks.saveProfile(alice,{...p,knowledge:'Verify the document type before entering fields.',reviewed:true},p.id);assert.equal(v2.revision,2);assert.throws(()=>f.tasks.saveProfile(alice,{...p,reviewed:true},p.id),{status:409});assert.equal(f.tasks.versions(alice,p.id).length,2);assert.ok(f.db.prepare('SELECT data_enc FROM task_profiles').all().every(r=>!r.data_enc.includes('Verify')));f.db.close();const reopened=openDatabase(f.dataDir,f.keyFile);try{const tasks=createTaskStore({...reopened,dataDir:f.dataDir,reader:f.reader});assert.equal(tasks.getProfile(alice,p.id).knowledge,v2.knowledge);assert.equal(tasks.versions(alice,p.id)[1].knowledge,p.knowledge);}finally{reopened.db.close();}});
test('learning cannot silently change a procedure or cross account boundaries',t=>{const f=fixture(t),p=f.tasks.saveProfile(alice,{name:'Fixture task',goal:'Verify a repeated task',instructions:'Inspect the current state first.',knowledge:'',reviewed:true});f.tasks.bind(alice,'run-fixture','chat-fixture',{profileId:p.id,revision:1,attachments:[]});const proposal=f.tasks.propose(alice,'run-fixture','chat-fixture','Inspect the offer label and verify the confirmation page.','Verified field mapping');assert.equal(f.tasks.getProfile(alice,p.id).revision,1);assert.throws(()=>f.tasks.review(bob,proposal.id,{approve:true,reviewed:true}),{status:404});assert.throws(()=>f.tasks.review(alice,proposal.id,{approve:true}),/Review/);f.tasks.review(alice,proposal.id,{approve:true,reviewed:true});assert.equal(f.tasks.getProfile(alice,p.id).revision,2);assert.equal(f.tasks.proposals(alice).length,0);f.tasks.bind(alice,'run-stale','chat-fixture',{profileId:p.id,revision:1,attachments:[]});const stale=f.tasks.propose(alice,'run-stale','chat-fixture','General safe steps','Observed steps');assert.throws(()=>f.tasks.review(alice,stale.id,{approve:true,reviewed:true}),{status:409});f.tasks.review(alice,stale.id,{approve:false});});
test('common personal identifiers, login secrets and credential URLs are not reusable knowledge',()=>{for(const value of ['Contact fixture@example.invalid','Tax code RSSMRA80A01H501Z','Payment IT00A0000000000000000000000','Phone +39 333 000 0000','password: fixture-secret','access_token=fixture-secret','https://fixture:secret@portal.example/form','https://portal.example/form?token=fixture-secret'])assert.throws(()=>assertReusable(value),/personal data/);assert.doesNotThrow(()=>assertReusable('Map customer.email to the Email field. Ask the user for consent.'));});
test('documents are encrypted, scoped to user and chat, integrity checked and expired',async t=>{const f=fixture(t),doc=await f.tasks.upload(alice,'chat-one','fixture.csv',Buffer.from('Field,Value\nOffer,TEST_PERSONAL_RECORD'));assert.equal(f.tasks.listAttachments(bob,'chat-one').length,0);assert.throws(()=>f.tasks.attachment(bob,doc.id),{status:404});assert.throws(()=>f.tasks.attachment(alice,doc.id,'chat-two'),{status:404});const raw=f.db.prepare('SELECT data_enc FROM chat_attachments').get().data_enc;assert.ok(!raw.includes('TEST_PERSONAL_RECORD'));const prepared=f.tasks.prepare(alice,'chat-one',[doc.id],false);assert.match(prepared.prompt,/TEST_PERSONAL_RECORD/);assert.ok(!prepared.prompt.includes('original'));const path=join(f.dataDir,'users',alice,'workspace',prepared.uploadFiles[0]);assert.equal(readFileSync(path,'utf8'),'Field,Value\nOffer,TEST_PERSONAL_RECORD');assert.equal(statSync(path).mode&0o077,0);const outside=join(f.root,'do-not-overwrite');writeFileSync(outside,'KEEP');unlinkSync(path);symlinkSync(outside,path);assert.throws(()=>f.tasks.prepare(alice,'chat-one',[doc.id],false),/Unsafe/);assert.equal(readFileSync(outside,'utf8'),'KEEP');f.tasks.clearMaterialized(alice,'chat-one');f.db.prepare('UPDATE chat_attachments SET expires_at=0').run();f.tasks.expire();assert.equal(f.db.prepare('SELECT count(*) n FROM chat_attachments').get().n,0);});
test('file validation rejects path injection, disguised binaries and invalid encodings',async t=>{const f=fixture(t);for(const name of ['../secret.txt','a/b.txt','a\\b.txt','.private.txt','evil.svg','evil.html','run.exe'])assert.throws(()=>documentType(name,Buffer.from('fixture')));assert.throws(()=>documentType('wrong.png',Buffer.from('%PDF-fixture')));await assert.rejects(f.reader.read('binary.txt',Buffer.from([0,255])),/UTF-8/);await assert.rejects(f.reader.read('binary.csv',Buffer.from('text\x00binary')),/Binary/);});
function pdf(objects){let out=Buffer.from('%PDF-1.4\n'),offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(out.length);out=Buffer.concat([out,Buffer.from(`${i+1} 0 obj\n`),Buffer.isBuffer(objects[i])?objects[i]:Buffer.from(objects[i]),Buffer.from('\nendobj\n')]);}const xref=out.length;out=Buffer.concat([out,Buffer.from(`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`+offsets.slice(1).map(x=>String(x).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`)]);return out;}
test('native sandboxed OCR reads JPG, PNG and scanned PDFs; PDF text extraction retains text',{skip:!browserAvailable?'Native browser unavailable':false},async t=>{const f=fixture(t);if(!f.reader.capabilities.ocr){t.skip('Install Tesseract or set SVOLO_OCR_PREFIX for native OCR checks');return;}const {evaluate}=await nativeBrowser(t,{handler:async(req,res)=>{res.writeHead(200,{'Content-Type':'text/html'});res.end('<html><body>OCR fixture</body></html>');return true;},ready:'document.body.textContent.includes("OCR fixture")'});const create=mime=>evaluate(`(()=>{const c=document.createElement('canvas');c.width=720;c.height=180;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,720,180);x.fillStyle='black';x.font='bold 42px sans-serif';x.fillText('TEST CONTRACT',25,60);x.fillText('PLAN ALPHA',25,130);return c.toDataURL(${JSON.stringify(mime)}).split(',')[1];})()`);let jpeg;for(const [name,mime]of[['fixture.png','image/png'],['fixture.jpg','image/jpeg']]){const bytes=Buffer.from(await create(mime),'base64');if(mime==='image/jpeg')jpeg=bytes;const value=await f.reader.read(name,bytes);assert.match(value.text,/TEST CONTRACT/);assert.match(value.text,/PLAN ALPHA/);assert.equal(value.method,'ocr');}
 const content='BT /F1 22 Tf 30 730 Td (TEST CONTRACT PLAN ALPHA readable text layer) Tj ET';const textPDF=pdf(['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Count 1 /Kids [3 0 R] >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${content.length} >>\nstream\n${content}\nendstream`]);const text=await f.reader.read('text.pdf',textPDF);assert.match(text.text,/readable text layer/);assert.equal(text.method,'pdf-text');
 const drawing='q 720 0 0 180 0 0 cm /Image Do Q';const scanned=pdf(['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Count 1 /Kids [3 0 R] >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 720 180] /Resources << /XObject << /Image 4 0 R >> >> /Contents 5 0 R >>',Buffer.concat([Buffer.from(`<< /Type /XObject /Subtype /Image /Width 720 /Height 180 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`),jpeg,Buffer.from('\nendstream')]),`<< /Length ${drawing.length} >>\nstream\n${drawing}\nendstream`]);const scan=await f.reader.read('scan.pdf',scanned);assert.match(scan.text,/TEST CONTRACT/);assert.equal(scan.method,'pdf-text+ocr');assert.equal(scan.pages,1);
 const header='BT /F1 12 Tf 30 210 Td (HEADER TEXT LAYER WITH MORE THAN THIRTY CHARACTERS) Tj ET';const mixedDrawing=header+'\n'+drawing;const mixed=pdf(['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Count 1 /Kids [3 0 R] >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 720 240] /Resources << /XObject << /Image 4 0 R >> /Font << /F1 6 0 R >> >> /Contents 5 0 R >>',Buffer.concat([Buffer.from(`<< /Type /XObject /Subtype /Image /Width 720 /Height 180 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`),jpeg,Buffer.from('\nendstream')]),`<< /Length ${mixedDrawing.length} >>\nstream\n${mixedDrawing}\nendstream`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>']);const mixedResult=await f.reader.read('mixed.pdf',mixed);assert.match(mixedResult.text,/HEADER TEXT LAYER/);assert.match(mixedResult.text,/PLAN ALPHA/);assert.equal(mixedResult.method,'pdf-text+ocr');assert.equal(readdirSync(join(f.root,'decode')).length,0);await assert.rejects(f.reader.read('broken.pdf',Buffer.from('%PDF-invalid')),/decoding failed/);assert.equal(readdirSync(join(f.root,'decode')).length,0);
});

test('custom profiles isolate many different tasks, users, selections and learned knowledge',t=>{
 const f=fixture(t);assert.deepEqual(f.tasks.listProfiles(alice),[]);assert.deepEqual(f.tasks.listProfiles(bob),[]);
 assert.throws(()=>f.tasks.saveProfile(alice,{name:'Unrequested template',template:'unsupported'}),/templates/);
 const inventory=f.tasks.saveProfile(alice,{name:'Inventory',goal:'Check stock differences',instructions:'Report discrepancies before changes.',knowledge:'Compare the SKU column with the Stock field.',uploadOrigins:['https://inventory.example'],reviewed:true});
 const review=f.tasks.saveProfile(alice,{name:'Document review',goal:'Review supplied documents',instructions:'List incomplete sections.',knowledge:'Verify the document section headings.',uploadOrigins:[],reviewed:true});
 const other=f.tasks.saveProfile(bob,{name:'Inventory',goal:'Prepare a private report',instructions:'Group results by category.',knowledge:'Compare the Category field.',uploadOrigins:[],reviewed:true});
 for(let i=0;i<40;i++)f.tasks.saveProfile(alice,{name:'Custom task '+i});assert.equal(f.tasks.listProfiles(alice).length,42);assert.equal(f.tasks.listProfiles(bob).length,1);
 f.tasks.select(alice,'one',inventory.id);f.tasks.select(alice,'two',review.id);f.tasks.select(bob,'one',other.id);
 const first=f.tasks.prepare(alice,'one',[],false),second=f.tasks.prepare(alice,'two',[],false),foreign=f.tasks.prepare(bob,'one',[],false);
 assert.ok(first.prompt.includes(inventory.instructions)&&first.prompt.includes(inventory.knowledge));assert.ok(!first.prompt.includes(review.instructions)&&!first.prompt.includes(other.knowledge));assert.ok(second.prompt.includes(review.goal)&&!second.prompt.includes(inventory.knowledge));assert.ok(foreign.prompt.includes(other.goal)&&!foreign.prompt.includes(inventory.instructions));
 f.tasks.bind(alice,'run-one','one',first.binding);f.tasks.select(alice,'one',review.id);
 const proposal=f.tasks.propose(alice,'run-one','one','Verified mapping: SKU to Item code.','Observed in the selected workflow');assert.equal(f.tasks.proposals(alice)[0].profileId,inventory.id);
 f.tasks.review(alice,proposal.id,{approve:true,reviewed:true});const learned=f.tasks.getProfile(alice,inventory.id);assert.equal(learned.goal,inventory.goal);assert.equal(learned.instructions,inventory.instructions);assert.equal(learned.revision,2);assert.equal(f.tasks.getProfile(alice,review.id).knowledge,review.knowledge);assert.equal(f.tasks.getProfile(bob,other.id).knowledge,other.knowledge);
 const restored=f.tasks.saveProfile(alice,{...f.tasks.versions(alice,inventory.id)[1],revision:learned.revision,reviewed:true},inventory.id);assert.equal(restored.revision,3);assert.equal(restored.instructions,inventory.instructions);assert.equal(restored.knowledge,inventory.knowledge);
 assert.throws(()=>f.tasks.select(alice,'one',other.id),{status:404});assert.throws(()=>f.tasks.saveProfile(alice,{name:'Unsafe',goal:'Contact unsafe@example.invalid',reviewed:true}),/personal data/);assert.throws(()=>f.tasks.saveProfile(alice,{name:'Unsafe',instructions:'password: fixture-secret',reviewed:true}),/personal data/);
 f.tasks.removeProfile(alice,review.id);assert.equal(f.tasks.selection(alice,'one'),'');assert.equal(f.tasks.selection(alice,'two'),'');assert.equal(f.tasks.getProfile(alice,inventory.id).revision,3);assert.equal(f.tasks.selection(bob,'one'),other.id);
});
test('pre-existing encrypted profile revisions have empty optional goal and instructions',t=>{
 const f=fixture(t),p=f.tasks.saveProfile(alice,{name:'Older user profile',knowledge:'Existing verified procedure',reviewed:true});const encoded=f.encrypt(JSON.stringify({name:p.name,knowledge:p.knowledge,uploadOrigins:[]}),alice+':profile:'+p.id);
 f.db.prepare('UPDATE task_profiles SET data_enc=? WHERE user_id=? AND id=?').run(encoded,alice,p.id);f.db.prepare('UPDATE task_profile_versions SET data_enc=? WHERE user_id=? AND profile_id=?').run(encoded,alice,p.id);
 assert.equal(f.tasks.getProfile(alice,p.id).goal,'');assert.equal(f.tasks.versions(alice,p.id)[0].instructions,'');assert.equal(f.tasks.getProfile(alice,p.id).knowledge,p.knowledge);
 const edited=f.tasks.saveProfile(alice,{...p,goal:'A custom goal',instructions:'A custom rule',reviewed:true},p.id);assert.equal(edited.revision,2);assert.equal(f.tasks.versions(alice,p.id)[1].knowledge,p.knowledge);
});
